---
- name: Configure Web Server on Ubuntu
  hosts: webserver
  become: yes
  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and Enable Nginx Service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Install iptables (if missing)
      apt:
        name: iptables
        state: present

    - name: Open Port 80 in Firewall using iptables
      shell: |
        sudo iptables -I INPUT -p tcp --dport 80 -j ACCEPT
        sudo netfilter-persistent save || true
      ignore_errors: yes
